---
apiVersion: v1
kind: Secret
metadata:
  name: $CLUSTER_NAME-bos
stringData:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: $CLUSTER_NAME
spec:
  monitoring:
    enablePodMonitor: true
  instances: 2
  storage:
    size: 10G
    storageClass: zfs
  walStorage:
    size: 10G
    storageClass: zfs
  resources:
    requests:
      cpu: 2
      memory: 4G
  postgresql:
    parameters:
      shared_buffers: 3GB
      wal_init_zero: "off" # zero-fill new WAL files
      wal_recycle: "off" # recycle WAL files
  backup:
    retentionPolicy: 15d
    barmanObjectStore:
      destinationPath: s3://$BUCKET_NAME/
      endpointURL: $AWS_ENDPOINT_URL
      data:
        compression: bzip2
      wal:
        compression: bzip2
      s3Credentials:
        accessKeyId:
          name: $CLUSTER_NAME-bos
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: $CLUSTER_NAME-bos
          key: AWS_SECRET_ACCESS_KEY
        region:
          name: $CLUSTER_NAME-bos
          key: AWS_DEFAULT_REGION
    volumeSnapshot:
      className: zfs
