apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: talos-setup
  namespace: zfs-system
spec:
  selector:
    matchLabels:
      app: zfs
  template:
    metadata:
      labels:
        app: zfs
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      volumes:
      - name: hostfs
        hostPath:
          path: /
      containers:
      - image: alpine
        name: zfsinfo
        volumeMounts:
        - name: hostfs
          mountPath: /hostfs
        securityContext:
          privileged: true
        command:
        - sh
        - -c
        - |
          while sleep 60; do
            echo ----------------------------------------
            date
            chroot /hostfs/ zpool list
            echo
            chroot /hostfs zfs list -o name,logicalreferenced,logicalused,referenced,quota,available,compression,compressratio
          done
      - name: zfsexporter
        image: alpine
        volumeMounts:
        - name: hostfs
          mountPath: /hostfs
        securityContext:
          privileged: true
        command:
        - sh
        - -c
        - |
          wget -O- https://github.com/pdf/zfs_exporter/releases/download/v2.3.4/zfs_exporter-2.3.4.linux-amd64.tar.gz \
          | tar -C /hostfs/var -zx --strip-components 1 'zfs_exporter-2.3.4.linux-amd64/zfs_exporter'
          exec chroot /hostfs /var/zfs_exporter
        ports:
        - name: metrics
          containerPort: 9134
      initContainers:
      - image: alpine
        name: setup
        volumeMounts:
        - name: hostfs
          mountPath: /hostfs
        securityContext:
          privileged: true
        command:
        - sh
        - -c
        - |
          set -e
          if ! chroot /hostfs zpool list zfspv-pool; then
            DEV=/dev/sdb
            echo "Creating zfspv-pool on $DEV."
            chroot /hostfs zpool create -m /var/zfspv-pool -o ashift=12 -O refreservation=10G zfspv-pool "$DEV"
          fi
          echo
          chroot /hostfs zpool list
          echo
          chroot /hostfs zfs list
